title: Harsh Baid
author: harshbaid
email: contact@harshbaid.in
description: > # this means to ignore newlines until "baseurl:"
  Inspired by Microsoft .NET and Sitecore

# social links
twitter_username: baid_harsh
github_username:  harshbaid

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
